### ISSUE TITLE
Configurable content directory

### ISSUE THREAD

**Issue by tmcw** [tmcw/notfoundbot#36]
This is currently hardcoded to _posts. I fear the complexity of the Full Solution to this problem but it looks like Hugo etc are being special, so allowing custom globs is probably necessary.

**Comment by tmcw** [comment]
I think this will require [actions/core](https://github.com/actions/toolkit/tree/main/packages/core) to read an option set in the workflow YAML.

**Comment by mattdsteele** [comment]
I have a need for this for my Gatsby-powered blog - I'll submit a PR when it's ready!
