### ISSUE TITLE
Use default github token

### ISSUE THREAD

**Issue by icco** [tmcw/notfoundbot#59]
In theory we shouldn't have to pass a token until we want to override the default: https://docs.github.com/en/actions/reference/authentication-in-a-workflow

Right now the action fails if no token is passed in.

**Comment by bensheldon** [comment]
My understanding of GitHub Actions is that `secrets.GITHUB_TOKEN` _must_ be explicitly referenced in the Workflow; 3rd-party Action steps cannot implicitly access it. 

The two methods are either via `ENV` or an Action's [`WITH` inputs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs) (which notfoundbot doesn't currently implement for passing the token).
